In [4]:
#incopy be a create a new object insted of shairing memory
x=[10]
y=x
y.append(4)

x


[10, 4]

In [23]:
#deepcopy
import copy
a=[10]
b=copy.deepcopy(a)
b.append(40)
b,a



([10, 40], [10])

In [3]:
#shallow copy 
import copy
original=[[1,2,3],45]
copy_list=original.copy()
copy_list[1]="abhishek"
copy_list.append("yes")
copy_list[0][1]="yadav"
print(copy_list)
original


[[1, 'yadav', 3], 'abhishek', 'yes']


[[1, 'yadav', 3], 45]

In [20]:
import numpy as nd
# a=nd.array([[[2,3]]])
# print(type(a))
# a.ndim
# print(np.__version__)
print(nd.ones(5))
a=print(nd.zeros(6))
print(nd.arange(5,8,2))
print(type(a))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]
[5 7]
<class 'NoneType'>


In [19]:
b=nd.array([[2,4,5,4],[5,4,5,6],[2,6,3,5]])
print(b.nbytes)
print(b.shape)
print(b.size)
print(b.ndim)


96
(3, 4)
12
2


In [28]:
# a=nd.array([1,2,3,6])
# b=nd.array([7,8,9,10])
# c=nd.array([11,12,13,14])
# print(nd.concatenate((a,b,c)))
# print(nd.vstack((a,b,c)))
# print(nd.hstack((a,b,c)))
# print(nd.split(a,4))

#searching
b=nd.array([1,2,3,4,5,6,8,7,9,10])
print(nd.where(b==9))
# nd.sort(b)
nd.argsort(b)


(array([8]),)


array([0, 1, 2, 3, 4, 5, 7, 6, 8, 9])

In [44]:
#filter
a=nd.array([1,2,3,6,5,4])
print(a[(a>2)&(a<5)])
print(a+10)


[3 4]
[11 12 13 16 15 14]
